variable "rg_name" {}
variable "location" {}
variable "vnet_name" {}
variable "subnet_name" {}
variable "address_space" {}
variable "address_prefixes" {}
variable "nic" {}
variable "vm_name" {}
variable "size" {}
variable "vm_username" {}
variable "vm_password" {}
variable "sku" {}
variable "img_version" {}